name: open-webui

summary: Open WebUI is a user-friendly AI Interface (Supports Ollama, OpenAI API, ...)
description: |
  Open WebUI is an extensible, feature-rich, and user-friendly self-hosted AI platform designed to operate entirely offline. 
  It supports various LLM runners like Ollama and OpenAI-compatible APIs, with built-in inference engine for RAG, making it a powerful AI deployment solution.

# license: unset # multiple licenses, see NOTICE file

base: core24
grade: stable
confinement: strict

adopt-info: version

platforms:
  amd64:
  arm64:

plugs:
  openai:
    interface: content
    content: owui-openai
    target: $SNAP/shared-configs
  ollama:
    interface: content
    content: owui-ollama
    target: $SNAP/shared-configs

parts:
  local:
    plugin: dump
    source: ./scripts
    organize:
      info.sh: bin/info.sh
      run-server.sh: bin/run-server.sh
      sync-configs.py: bin/sync-configs.py

  open-webui:
    plugin: python
    source: dependencies
    build-packages:
      - python3-minimal
      - python3-venv
      - python3-dev
      - python3-pip
      - git
    stage-packages:
      - python3-minimal
    python-requirements:
      - requirements.txt
    override-build: |
      # The python plugin fails if we run the build while files from a previous build exist in the install dir
      rm -rf $CRAFT_PART_INSTALL/*
      
      craftctl default
      
      # Remove GPU-specific pytorch and its dependencies
      pip install pip-autoremove
      pip-autoremove torch -y
      rm -rf $CRAFT_PART_INSTALL/lib/python*/site-packages/nvidia
      rm -rf $CRAFT_PART_INSTALL/lib/python*/site-packages/torch
      
      # Install CPU-only pytorch
      pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    
  version:
    after:
      - open-webui
    plugin: nil
    # Use repo root as source to force recalculating the version on any change
    source: .
    override-prime: |
      owui_version="$(python3 -m pip show open-webui | grep Version: | awk '{print $2}')"
      snap_packaging_commit="$(git -C $SNAPCRAFT_PROJECT_DIR describe --always --dirty)"

      # Set the snap's version
      craftctl set version="$owui_version+snap.$snap_packaging_commit"

  license:
    after:
      - open-webui
    plugin: nil
    source: .
    override-prime: |
      # Copy Open WebUI license files to a more visible location
      cp -vr $CRAFT_STAGE/lib/python*/site-packages/open_webui-*.dist-info/licenses $CRAFT_PRIME/open-webui-licenses
      
      # Add the NOTICE file
      cp -v $CRAFT_PROJECT_DIR/NOTICE $CRAFT_PRIME/

apps:
  open-webui:
    command: bin/info.sh

  server:
    command: bin/run-server.sh
    daemon: simple
    install-mode: enable
    restart-condition: on-failure
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
    environment:
      ENV: prod
      DATA_DIR: $SNAP_COMMON/data
      STATIC_DIR: $SNAP_DATA/static
      ENABLE_VERSION_UPDATE_CHECK: "false"
