name: Build main branch
# This workflow requires a STORE_LOGIN secret that can publish to latest/edge and promote to latest/beta. e.g:
# snapcraft export-login --snaps=open-webui --acls package_access,package_push,package_update,package_release --channels latest/edge,latest/beta --expires "2027-01-31T00:00:00Z" secret-main.txt

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}

jobs:
  build-publish-test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Refresh/Install snapd
        run: sudo snap refresh snapd || sudo snap install snapd

      - name: Checkout
        uses: actions/checkout@v7

      - name: Build snap
        id: build
        uses: canonical/action-build@v1

      - name: Publish to latest/edge
        uses: canonical/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: latest/edge

      - name: Install Python Venv
        run: sudo apt-get install -y python3-venv

      - name: Run smoke tests
        env:
          OWUI_CHANNEL: latest/edge
        run: ./tests/smoke/run.sh

      - name: Run upgrade tests
        env:
          OWUI_FROM_CHANNEL: latest/stable
          OWUI_CHANNEL: latest/edge
        run: ./tests/upgrade/run.sh

  promote-beta:
    needs: build-publish-test
    runs-on: ubuntu-latest
    steps:
      - name: Refresh/Install snapd
        run: sudo snap refresh snapd || sudo snap install snapd

      - name: Install snapcraft
        run: sudo snap install snapcraft --classic

      - name: Promote latest/edge to latest/beta
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        run: |
          snapcraft promote open-webui --yes \
            --from-channel latest/edge \
            --to-channel latest/beta
