name: Build main branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ self-hosted, amd64, noble, medium ]
          - [ self-hosted, arm64, noble, medium ]
    with:
      runner: "${{ toJSON(matrix.runner) }}"
      publish-channel: 'latest/edge' # Add track if needed, e.g., 24/latest/edge
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN }}

  smoke-test:
    needs: build-and-publish
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ self-hosted, amd64, noble, medium ]
          - [ self-hosted, arm64, noble, medium ]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run smoke tests
        run: ./tests/run-smoke-tests.sh --channel latest/edge

