name: Build and test PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Refresh/Install snapd
        run: sudo snap refresh snapd || sudo snap install snapd

      - name: Checkout
        uses: actions/checkout@v7
        with:
          # Prevent usage of simulated merge commit of PR
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Build snap
        id: build
        uses: canonical/action-build@v1

      - name: Upload snap artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.build.outputs.snap }}
          archive: false
          if-no-files-found: error

      - name: Install Python Venv
        run: sudo apt-get install -y python3-venv

      - name: Run smoke tests
        env:
          OWUI_SNAP: ${{ steps.build.outputs.snap }}
        run: ./tests/smoke/run.sh

      - name: Run upgrade tests
        env:
          OWUI_FROM_CHANNEL: latest/edge
          OWUI_SNAP: ${{ steps.build.outputs.snap }}
        run: ./tests/upgrade/run.sh
