#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.connect-plug-ollama"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

echo "Connected Ollama plug"

python3 $SNAP/bin/sync-configs.py
